### PR TITLE
[WIP] Add Typescript support

### PR DESCRIPTION
**Pull request by HelloEdit**
Hello,

I have started to write the basis of TypeScript definitions, but I am not yet an expert on this subject. I do not think I can go any further in what I have written, in particular about the mutation of the instance object. I think the advice of someone more experienced would be greatly appreciated.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you:

* [ ] remove package-lock.json and add it to .gitignore
* [ ] add a typescript test https://github.com/fastify/fastify/blob/master/package.json#L10

Considering the fact that avvio could extend a server with a given key (remap `use` to `register` for example), how do you plan to map that in TypeScript?

**Comment by HelloEdit** [comment]
Just found this: https://gitlab.com/seangenabe/types-avvio/blob/master/index.d.ts. I think it's an avvio approach as a class.

**Comment by mcollina** [comment]
I'm good either way. Let me know if you still want to pursue this.

**Comment by HelloEdit** [comment]
Hi, I accidentally deleted the fork from the repository :(
I have updated the definitions you can find above:
```js
// Type definitions for avvio
// Project: https://github.com/mcollina/avvio
// Definitions by: HelloEdit https://github.com/HelloEdit/
/// <reference types="node" />
declare function avvio<T = any>(
  server: T,
  done: () => void
): avvio.BootInstance<T>

declare function avvio<T = any>(
  server?: T,
  opts?: avvio.AvvioOptions,
  done?: () => void
): avvio.BootInstance<T>

declare namespace avvio {
  export interface AvvioOptions {
    autostart?: boolean
    expose?: ExposeOptions
  }

  export interface ExposeOptions {
    use?: string
    after?: string
    ready?: string
  }

  export interface BootInstance<T> extends Application<T> {
    started: boolean
    booted: boolean
    start(): this
  }

  // See (https://github.com/mcollina/avvio/pull/61#issuecomment-382685734)
  export interface Application<T> {
    use(func: (server: BootInstance<T>, opts: string) => Promise<void>): this
    use(
      func: (server: BootInstance<T>, opts: any, done: () => void) => void
    ): this

    after(func?: (err: any) => void): this
    after(func?: (err: any, done: () => void) => void): this
    after(
      func?: (err: any, context: BootInstance<T>, done: () => void) => void
    ): this

    ready(): Promise<any>
    ready(func?: (err: any) => void): any
    ready(func?: (err: any, done: () => void) => void): any
    ready(
      func?: (err: any, context: BootInstance<T>, done: () => void) => void
    ): any

    onClose(func: (context: BootInstance<T>) => void): void
    onClose(func: (context: BootInstance<T>, done: () => void) => void): void

    // TODO: override
    close(func: (err: any) => void): void
    close(func: (err: any, done: () => void) => void): void
    close(
      func: (err: any, context: BootInstance<T>, done: () => void) => void
    ): void
  }

  export function express<T = any>(server?: T): avvio.BootInstance<T>
}

export default avvio
```

If you write the following code:
```js
import avvio from 'avvio'

let server: avvio.Applica
const a
```

**Pull request closed without merging**
